# Generated by Django 3.0.4 on 2021-01-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemadata',
            name='column_separator',
            field=models.CharField(choices=[('1', 'Comma (,)'), ('2', 'Colon (;)')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='schemadata',
            name='string_character',
            field=models.CharField(choices=[('1', 'Double-quote (")'), ('2', "Quote (')")], default=1, max_length=50),
        ),
    ]
