# Generated by Django 3.0.4 on 2021-01-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20210131_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaset',
            name='link_download',
            field=models.CharField(blank=True, max_length=248),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='type',
            field=models.CharField(choices=[('1', 'Job'), ('2', 'Domain name'), ('3', 'Phone Number'), ('4', 'Company'), ('5', 'Integer')], default=1, max_length=25),
        ),
        migrations.AlterField(
            model_name='schemaset',
            name='status',
            field=models.CharField(choices=[('1', 'Processing'), ('2', 'Ready')], max_length=15),
        ),
    ]
