# Generated by Django 3.0.4 on 2021-01-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20210131_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='extra_data_type',
            field=models.CharField(default='from=10 to=50', max_length=1024),
            preserve_default=False,
        ),
    ]
