# Generated by Django 3.0.4 on 2021-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20210131_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaset',
            name='link_download',
            field=models.CharField(max_length=248),
        ),
    ]
