# Generated by Django 3.0.4 on 2021-02-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_auto_20210201_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaset',
            name='link_download',
            field=models.CharField(blank=True, max_length=248),
        ),
    ]
