# Generated by Django 3.0.4 on 2021-02-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_auto_20210201_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemaset',
            options={},
        ),
    ]
